version: "3"

services:
  activemq:
    image: rmohr/activemq
    ports:
      - '61616:61616'
      - '8161:8161'
    networks:
      - usp

  obuspa:
    image: obuspa
    volumes:
      - ./config:/app/config
    networks:
      - usp

networks:
  usp:
    driver: bridge



